

# import urllib.parse as urlparse
# import psycopg2                 # for python 3+ use: from urllib.parse import urlparse
# from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT




# con.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
# cur = con.cursor()
# cur.execute(
#     '''
#         CREATE TABLE tb_typeimageproduct (
#             type varchar(20) not null,
#             image text not null
#         )
#         CREATE TABLE tb_product (
#             idproduct INT GENERATED BY DEFAULT AS IDENTITY 
#             (START WITH 2000154 INCREMENT BY 1) PRIMARY KEY,
#             nameproduct VARCHAR(100) NOT NULL,
#             amount int not null,
#             material varchar(50),
#             details varchar(1000)
#         )
#         CREATE TABLE tb_headimage (
#             idproduct INTEGER NOT NULL,
#             image text not null,
#             FOREIGN KEY (idproduct)
#                     REFERENCES tb_product (idproduct)
#                     ON UPDATE CASCADE ON DELETE CASCADE
#         );
#         CREATE TABLE tb_colors (
#             idproduct INTEGER NOT NULL,
#             price int NOT NULL,
#             amount int NOT NULL,
#             colors varchar(20) NOT NULL,
#             size varchar(10) NOT NULL,
#             FOREIGN KEY (idproduct)
#                     REFERENCES tb_product (idproduct)
#                     ON UPDATE CASCADE ON DELETE CASCADE
#         );
#     ''')
# cur.close()
# con.close()